### ISSUE TITLE
Chap. 7, Fig. 7.1

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#109]
Ma figure est vraiment trop moche, je m'en rends bien compte après l'avoir projetée en classe. Je dirais à refaire absolument avec les belles fontes du sylabus (sinon à virer) pour l'année prochaine.

**Comment by mcodutti** [comment]
Eyhtan, tu as l'occasion de le faire mieux ?

**Comment by eythanlevy** [comment]
Je viens de pusher une version améliorée
