### ISSUE TITLE
Ch. 7

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#111]
Je propose de remettre aussi dans le chapitre 7 l'équivalent des sections 5.6.2 et 5.6.3 concernant le "demander" et la préférence de paramètres. Un tel exemple (comme celui du 5.6.3) avec un algo test contenant "demander" et "afficher" aurait aussi sa place dans ce chapitre 7, par souci de complétude du chapitre, même si cela a déjà été brièvement vu auparavant.

**Comment by mcodutti** [comment]
Je ne trouve pas les sections 5.6.2 et .3 dans le document. Tu peux être plus précis ?

**Comment by mcodutti** [comment]
Demande imprécise :(
