### ISSUE TITLE
Ch. 6 ex. 18

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#113]
Exo "Réussir GEN1":
-Dire si la moyenne doit être sur 20 ou sur 100
-Donner les pondérations (car l'info n'est pas facile à trouver par eux en cours (pas de PC) et aussi l'info n'est pas clairement mise sur le site de l'ESI car il n'y a que les ECTS, avec le cours de méthodo en plus...). Cela fait perdre bcp de temps. Pq ne pas juste donner les pondérations dans l'énoncé, ainsi que le nom des 3 AA?

**Comment by ahallal** [comment]
Salut,
La ponderation se trouve dans le document ''évaluation'' qui se trouve en
bas de page. Tu trouves 60 % pour math' 20 et 20 pour les deux autres. Dans
mon cas, il etait interessant de leur montrer l'endroit ou se trouvait les
ponderations et par de même comment les cotes UE sont calculées.
Le 28 oct. 2015 10:45, "eythanlevy" <notifications@github.com> a écrit :

> -Dire si la moyenne doit être sur 20 ou sur 100
> -Donner les pondérations (car l'info n'est pas facile à trouver par eux en
> cours (pas de PC) et aussi l'info n'est pas clairement mise sur le site de
> l'ESI car il n'y a que les ECTS, avec le cours de méthodo en plus...). Cela
> fait perdre bcp de temps. Pq ne pas juste donner les pondérations dans
> l'énoncé, ainsi que le nom des 3 AA?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/issues/113>.
>

-- 
Haute École de Bruxelles

**Comment by mcodutti** [comment]
J'ai cherché quelques minutes sur le site de l'ÉSI et sur poÉSI et je n'ai pas trouvé l'information. J'ai donc suivi Eythan et été plus explicite dans l'énoncé.
