### ISSUE TITLE
Chap. 6 exo 15: Tirer une carte

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#114]
Je pense qu'il faut préciser l'encodage de la carte dans l'énoncé car la difficulté est très variable en fonction de cet encodage, donc il faut qu'on décide en amont ce que nous voulons que cet exercice évalue. Je préfère l'encodage par deux entiers [1-13] et [1-4] que un seul entier [1-52]. Car dans le second cas la solution est bcp plus compliquée, et aussi le premier cas présente l'avantage de leur montrer la génération aléatoire d'un objet par deux tirs successifs du générateur uniforme.

**Comment by npettiaux** [comment]
Effectivement. L'énoncé présenté pour le moment requiert des précisions nécessaires pour pouvoir être effectué. pour moi, cet exercice veut fait utiliser MOD et DIV (ce qui est difficile pour beaucoup d'étudiants car ils n'en ont pas l'habitude). l'encodage Par exemple (ce que j'ai dit) :" chaque carte est associée à une entier de 1 à 52. Toutes les cartes d'une couleur sont rangées par ordre croissant, une couleur à la suite d'une autre"
