### ISSUE TITLE
chap 9 (tableaux) - initialisation compacte

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#115]
Je n'aime pas trop l'initialisation 
tab <-   {0, 1, 2, . . .}
car elle ouvre la porte à faire n'importe quelle suite de manière automatisée, donc pour un exo de suite à l'examen ils pourraient faire cela en une ligne dans un tableau directement... De plus il est difficile de dire pour quelles suite cela est permis et pour lesquelles pas P.ex. est-ce que ceci est permis? : 
tab <- {1,2,3, ...}
ou ceci : 
tab <- {2, 4, 6, ...} 
Je propose donc de virer cela, qui de plus ne correspond à rien dans les langages genre Java, C, C++

**Comment by ahallal** [comment]
Je partage ton avis.
Le 27 nov. 2015 09:20, "eythanlevy" <notifications@github.com> a écrit :

> Je n'aime pas trop l'initialisation
> tab <- {0, 1, 2, . . .}
> car elle ouvre la porte à faire n'importe quelle suite de manière
> automatisée, donc pour un exo de suite à l'examen ils pourraient faire cela
> en une ligne dans un tableau directement... De plus il est difficile de
> dire pour quelles suite cela est permis et pour lesquelles pas P.ex. est-ce
> que ceci est permis? :
> tab <- {1,2,3, ...}
> ou ceci :
> tab <- {2, 4, 6, ...}
> Je propose donc de virer cela, qui de plus ne correspond à rien dans les
> langages genre Java, C, C++
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/issues/115>.
>

-- 
Haute École de Bruxelles
