### ISSUE TITLE
chap 9 (tableaux) - exercice 8

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#116]
Je n'aime pas trop cet exercice car il demande juste de retourner n alors qu'on s'attend à un algo avec une boucle (ce que font la plupart des étudiants, avec un compteur).

**Comment by cathleruste** [comment]
Justement, c'est pour ça que je l'aime bien, moi. Il me permet de leur dire "Réfléchissez 2 minutes avant de vous lancer dans l'écriture d'une solution"
