### ISSUE TITLE
chap 9 (tableaux) - exercices 10-11 (parcours partiel)

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#117]
Les exercices 10 et 11 me semblent trop proches car ils testent exactement la même compétence. Je propose de n'en garder que un des deux, idéalement le même que "pilote dans l'avion" mais avec des entiers au lieu des strings car c'est plus facile à visualiser et à dessiner au tableau (donc recherche d'un entier précis, par opposition à la recherche de n'importe quel négatif)..

**Comment by mcodutti** [comment]
J'ai enlevé le premier (recherche d'un négatif) et j'ai transformé celui de l'avion en une recherche de 20 dans un tableau de cotes. J'en ai fait 2 versions : au moins une fois 20 et exactement une fois 20.
