### ISSUE TITLE
chap 12 exo 7b

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#121]
Je trouve cela fort difficile  et peu intéressant. Si on legarde, alors devrait faire l'objet d'une question à soi tout seul car fort difficile.

**Comment by eythanlevy** [comment]
Globalement l'exercice 7 a trop de questions, sous-questions, variantes et sous-variantes. Il faut garder des énoncés plus courts et plus simples à mon avis.

**Comment by mcodutti** [comment]
Je ne trouve pas cette question dans le chapitre 12
