### ISSUE TITLE
CHap 14: structures - imbrication de structures

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#126]
Prévoir un exemple avec un champ d'une structure qui est lui même de type structuré. Pour l'instant ce n'est que en exo mais pas illustré par un exemple dans la théorie.

**Comment by mcodutti** [comment]
Ajouté une petite section avec un exemple Personne qui a une date de naissance et 3 num. de tél + exemple d'utilisation.
