### ISSUE TITLE
Place de la numérotation pour consistance et facilité 

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/DEV1-ALG-Syllabus-Algo#128]
L'endroit où la numérotation apparaît sur la page n'est pas fixe. C'est troublant quand on parcourt le syllabus à la recherche d'une information. Sur les pages de chapitre, c'est au milieu du bas de la page, pour les autres dans le coin supérieur extérieur.  Cette dernière solution partout serait plus facile et plus agréable, je pense (Les pages de séparation de parties devraient aussi porter un numéro.)

**Comment by mcodutti** [comment]
Je n'ai pas rapidement trouvé comment faire.
Je veux bien un peu d'aide...
