### ISSUE TITLE
Tableaux: création de tableaux dont la taille n'est pas encore connue

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#129]
La nouvelle syntaxe du syllabus pour la création de tableaux dont la taille n'est pas encore connue me pose problème (p. 92 du syllabus). P.ex. dans les années précédents, si on voulait appeler une fonction qui retourne un tableau, on déclarait d'abord un tableau sans taille (p.ex. "tab: tableau d'entiers") et puis on faisait "tab <- créerTableau(n)" par exemple. 
Dans la nouvelle syntaxe, on ne peux plus faire ça, car on a besoin d'une taille de tableau dès la déclaration, comme dans l'exemple de la p. 92:
entiers : tableau de 20 entiers
entiers <- créer(20)

Ceci suppose qu'on connait déjà la taille du tableau à la déclaration car on a déjà dû mettre 20 à la déclaration. Mais quid si on ne connait pas cette taille? Si p.ex. elle est choisie intéractivement par l'utilisateur? Que mets-je alors comme taille dans la déclaration de mon tableau? D'autant plus que dans notre langage les variables (donc aussi les tableaux) sont obligatoirement déclarés en début de module donc on ne peut même pas d'abord établir la taille dans une variable puis déclarer le tableau. C'est assez embêtant je trouve. Ou bien je n'ai pas saisi qqch, ou manqué qqch dans le syllabus? 
Si réellement ce problème existe, alors à mon avis cela pointe vers le besoin d'adopter un langage, pour ce cours de première introduction au développement, dont la syntaxe et la sémantique soit rigoureusement définies (et standardisées) afin de ne pas tomber sur des problèmes de ce genre. Car un langage inventé par nos soins, et évoluant d'année et année, ne manquera pas de toujours contenir des imprécisions de ce genre il me semble. A réfléchir en équipe, bien évidemment...

**Comment by ahallal** [comment]
Salut Eythane et bonne année. 
Pour ta question je dirai
Tableau dynamique alors. Avec la syntaxe nouveau tableau..,,, 
Pas vu au  1er semestre et pas eu Besoin. Voir si DEV2 en parle....
  

Amine HALLAL

Maître assistant en informatique


> Le 3 janv. 2016 à 12:59 PM, eythanlevy <notifications@github.com> a écrit :
> 
> La nouvelle syntaxe du syllabus pour la création de tableaux dont la taille n'est pas encore connue me pose problème (p. 92 du syllabus). P.ex. dans les années précédents, si on voulait appeler une fonction qui retourne un tableau, on déclarait d'abord un tableau sans taille (p.ex. "tab: tableau d'entiers") et puis on faisait "tab <- créerTableau(n)" par exemple. 
> Dans la nouvelle syntaxe, on ne peux plus faire ça, car on a besoin d'une taille de tableau dès la déclaration, comme dans l'exemple de la p. 92:
> entiers : tableau de 20 entiers
> entiers <- créer(20)
> 
> Ceci suppose qu'on connait déjà la taille du tableau à la déclaration car on a déjà dû mettre 20 à la déclaration. Mais quid si on ne connait pas cette taille? Si p.ex. elle est choisie intéractivement par l'utilisateur? Que mets-je alors comme taille dans la déclaration de mon tableau? D'autant plus que dans notre langage les variables (donc aussi les tableaux) sont obligatoirement déclarés en début de module donc on ne peut même pas d'abord établir la taille dans une variable puis déclarer le tableau. C'est assez embêtant je trouve. Ou bien je n'ai pas saisi qqch, ou manqué qqch dans le syllabus? 
> Si réellement ce problème existe, alors à mon avis cela pointe vers le besoin d'adopter un langage, pour ce cours de première introduction au développement, dont la syntaxe et la sémantique soit rigoureusement définies (et standardisées) afin de ne pas tomber sur des problèmes de ce genre. Car un langage inventé par nos soins, et évoluant d'année et année, ne manquera pas de toujours contenir des imprécisions de ce genre il me semble. A réfléchir en équipe, bien évidemment...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Haute École de Bruxelles

**Comment by eythanlevy** [comment]
Merci Amine et bonne année à toi aussi! Je me suis posé cette question dans
le cadre d'une rédaction d'examen même si en effet le besoin n'en est pas
apparu chez moi non plus en donnant le cours au 1er semestre.
Le 3 janv. 2016 14:58, "ahallal" <notifications@github.com> a écrit :

> Salut Eythane et bonne année.
> Pour ta question je dirai
> Tableau dynamique alors. Avec la syntaxe nouveau tableau..,,,
> Pas vu au 1er semestre et pas eu Besoin. Voir si DEV2 en parle....
>
>
> Amine HALLAL
>
> Maître assistant en informatique
>
>
> > Le 3 janv. 2016 à 12:59 PM, eythanlevy <notifications@github.com> a
> écrit :
> >
> > La nouvelle syntaxe du syllabus pour la création de tableaux dont la
> taille n'est pas encore connue me pose problème (p. 92 du syllabus). P.ex.
> dans les années précédents, si on voulait appeler une fonction qui retourne
> un tableau, on déclarait d'abord un tableau sans taille (p.ex. "tab:
> tableau d'entiers") et puis on faisait "tab <- créerTableau(n)" par
> exemple.
> > Dans la nouvelle syntaxe, on ne peux plus faire ça, car on a besoin
> d'une taille de tableau dès la déclaration, comme dans l'exemple de la p.
> 92:
> > entiers : tableau de 20 entiers
> > entiers <- créer(20)
> >
> > Ceci suppose qu'on connait déjà la taille du tableau à la déclaration
> car on a déjà dû mettre 20 à la déclaration. Mais quid si on ne connait pas
> cette taille? Si p.ex. elle est choisie intéractivement par l'utilisateur?
> Que mets-je alors comme taille dans la déclaration de mon tableau? D'autant
> plus que dans notre langage les variables (donc aussi les tableaux) sont
> obligatoirement déclarés en début de module donc on ne peut même pas
> d'abord établir la taille dans une variable puis déclarer le tableau. C'est
> assez embêtant je trouve. Ou bien je n'ai pas saisi qqch, ou manqué qqch
> dans le syllabus?
> > Si réellement ce problème existe, alors à mon avis cela pointe vers le
> besoin d'adopter un langage, pour ce cours de première introduction au
> développement, dont la syntaxe et la sémantique soit rigoureusement
> définies (et standardisées) afin de ne pas tomber sur des problèmes de ce
> genre. Car un langage inventé par nos soins, et évoluant d'année et année,
> ne manquera pas de toujours contenir des imprécisions de ce genre il me
> semble. A réfléchir en équipe, bien évidemment...
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> --
> Haute École de Bruxelles
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/issues/129#issuecomment-168500374>
> .
>

-- 
Haute École de Bruxelles

**Comment by npettiaux** [comment]
La question de Ethan est très pertinente.

**Comment by ahallal** [comment]
Qu'est ce qui est a été décidé ? Un rendez-vous pour en discuter ? 
En effet pour un tableau de ce genre l n'y a rien pour l'instant !  

Hallal amine
Maître assistant à l'ESI
