### ISSUE TITLE
annexe B : plusieurs retourner

### ISSUE THREAD

**Issue by npettiaux** [HEB-ESI/DEV1-ALG-Syllabus-Algo#139]
J'apprécie que l'on autorise explicitement de sortir d'une boucle pour par un retourner. 

On pourrait dire que la sortie d'une boucle par un break est aussi autorisée. C'est la même chose et est uen habitude dans certains langages. 

Il faut aussi gérer (au moins décrire) la contradiction avec le point 2 du B4 ("nous tenons absolument à ce que vous passiez par une boucle tant-que et l'utilisation d'un booléen pour controler la fin")

Je crois qu'il faut encore une fois insister sur le fait que si cela simplifie l'écriture et la compréhension des algorithmes, c'est acceptable.

**Comment by ahallal** [comment]
Je reste persuadé que ce n'est pas une bonne idée de quitter un pour avec un return. 

Hallal amine
Maître assistant à l'ESI
