### ISSUE TITLE
Chapitre 5

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV1-ALG-Syllabus-Algo#141]
Ex 17 : on parle de regarder si sa cote est de plus de 18/20, on s'attend à comparer avec 18, avec 0.9 ou à lancer une discussion sur les différentes possibilités ?

**Comment by mcodutti** [comment]
Dans ma tête, on a une cote qui est un entier entre 0 et 20 et on compare simplement à 18 (cf. exemple plus haut) mais ça peut être l'occasion de lancer la discussion si des étudiants pensent à autre chose.
