### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by arthur92** [HEB-ESI/DEV1-ALG-Syllabus-Algo#142]
Je sais pas si on modifie et commit directement les fautes d'orthographe mais dans le doute je la met ici 
Page 19 (section 3.2) Paragraphe juste avant la conclusion : 
Certains problèmes sont suffisamment simples QUE pour être directement programmés. 

Le que n'est pas français, il faudrait que ce soit : Certains problèmes sont suffisamment simples pour être directement programmés.

**Comment by YoungFrog** [comment]
À mon avis pour ce genre de chose tu commit directement. Si t'es vraiment pas sûr tu fais une pull request pour ouvrir la discussion. Pour ce que ça vaut je suis d'accord avec cette modif. D'après un blog trouvé au hasard d'une recherche ce serait un belgicisme. (http://belgicisme.blogg.org/que-pour-trop-assez-a116055884)

**Comment by YoungFrog** [comment]
Closed by https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/commit/1f7aff3a86f5adb24330f9ee2e37a5ad0f4dc11f
