### ISSUE TITLE
Chapitre 3 : Ressources

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV1-ALG-Syllabus-Algo#143]
Sauf erreur de ma part, le lien https://www.youtube.com/watch?v=TIkBcrbzYf0 est mort.
Quelqu'un peut confirmer ?

**Comment by mcodutti** [comment]
Je confirme.
On peut le remplacer par un "C'est pas sorcier !" sur l'informatique.
https://www.youtube.com/watch?v=c96KP5jZVYk
