### ISSUE TITLE
chapitre 5  partie 5.3

### ISSUE THREAD

**Issue by ahallal** [HEB-ESI/DEV1-ALG-Syllabus-Algo#145]
Dans la partie 5.3
Remplacer dans la phrase le mot "se site" par se situe:

Parfois, le problème se site au niveau de la compréhension du vocabulaire

**Comment by YoungFrog** [comment]
Déjà arrangé dans 9a21d630e5ee15232f26ebd6b1290d4f77d268e2
Merci,

Nicolas.
