### ISSUE TITLE
ch 1 ressources : compléments 

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#27]
Les Sépas 11 Un bug : https://www.youtube.com/watch?v=deI0GV5sWTY trouvé sur 
https://www.youtube.com/user/Scienceparticipative/videos via pixees.fr où les vidéos "Le jeu de Nim comme algorithme" , "Le Crépier psycho-rigide comme algorithme", "Le baseball multicouleur comme algorithme",... sont pour ma part tb. Pourquoi pas mettre en pratique ces jeux puis montrer la vidéo?

**Comment by mcodutti** [comment]
Très chouettes exemples; je les ai ajoutés comme ressources en fin de chapitre 1.
Je ne suis pas sûr qu'on ait le temps de tout faire en classe mais on peut en faire certains en fonction de nos envies
