### ISSUE TITLE
Idées d'animations 

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#28]
Utiliser la visualisation algorithmique pour faciliter l’apprentissage des algorithmes : http://www.xplora.org/ww/fr/pub/xplora/practice/examples/algorithm.htm

**Comment by cuv** [comment]
Comment mon ordinateur réfléchit ? Processeur RAM Disque dur : https://www.youtube.com/watch?v=TIkBcrbzYf0

**Comment by mcodutti** [comment]
"Comment mon ordinateur réfléchit ?" m'a l'air plus approprié pour les cours d'intro comme "Intro à l'ordinateur".

**Comment by cuv** [comment]
il illustre le §3.1.3. Ce chapitre est peut être déjà donné dans un cours
d'intro?

2015-05-02 21:48 GMT+02:00 Marco Codutti <notifications@github.com>:

**Comment by mcodutti** [comment]
J'espère que c'est plus et mieux expliqué en "intro ordinateur".
J'ajoute une section "ressources" avec ce lien en fin de chapitre.
