### ISSUE TITLE
§ 531 Ajouter rappel table vérité loi de De Morgan ?  

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#29]
J'ajouterais un rappel sur les booléens (tables de vérité Et et Ou et loi de De Morgan par exemple) C'est vu en math  mais un rappel me semble bien ici.

**Comment by cuv** [comment]
l'exercice 13 vient trop tôt, les opérateurs logiques sont vus plus loin.

**Comment by cuv** [comment]
Je propose de mettre le § 532 après le 533, de faire des exercices sans Et et OU dans le 531.

**Comment by mcodutti** [comment]
Bien vu.
J'ai aussi ajouté un petit texte sur les parenthèses.
