### ISSUE TITLE
ajouter demande de tests

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#31]
Aux phrases qui introduisent les exercices du genre "Pour chacun des exercices suivants, on vous demande" ajouter un dernier point: tester vos solutions

**Comment by mcodutti** [comment]
J'ai un peu travaillé la présentation du traçage d'algorithme. cf. $5.2.3 et 5.2.4.
J'ai introduit des numéros de lignes dans ces algorithmes pour plus de clarté.
Est-ce que ça convient ? Est-ce que vous voyez une façon plus claire de présenter les choses ?

**Comment by cuv** [comment]
pour moi c'est une belle amélioration. J'essayerais d'afficher les numéros
de ligne dans une autre police/couleur pour mieux les distingués du code.

**Comment by cuv** [comment]
ajouter cette demande en 6.2.1, 6.3.1, 6.4.1, 6.5.1,...

**Comment by cuv** [comment]
Faire un exemple de traçage pour le chapitre module. Ajouter la demande aux exercices

**Comment by mcodutti** [comment]
J'ai encore retravaillé un peu tout ce qui concerne la vérification et le traçage pour le chapitre 5.
Je le ferai pour les autres chapitres au fur et à mesure de la relecture.

**Comment by mcodutti** [comment]
J'ai ajouté ceci au point 5.1.2 (Vérifier algorithme) :
Attention : Dans tous les exercices qui suivront, chaque fois qu’on vous demandera d’écrire
un algorithme, on attendra de vous : de spécifier le problème, de fournir des exemples,
d’écrire l’algorithme et de le vérifier sur vos exemples. Ce n’est que si tous ces éléments sont
présents que votre solution pourra être considérée comme complète.

**Comment by mcodutti** [comment]
Je dois encore retravailler le traçage pour le chapitre sur la décomposition modulaire.

**Comment by cathleruste** [comment]
Ça me parait ok pour le traçage dans le ch.7
