### ISSUE TITLE
Fiche: ajouter liste numéros exercices

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#35]
Pour un travail en autonomie, j'ajouterais une liste de numéros d'exercices à chaque fiche.  Il faudrait aussi réfléchir à une auto-évaluation (problème fort difficile.... j'ai pas de bonnes idées).

**Comment by mcodutti** [comment]
Est-ce que qqun veut choisir une fiche et dresser la liste des exercices qui s'y rapportent ?

**Comment by cathleruste** [comment]
Je ne suis pas emballée par cette idée.
- C'est une grosse contrainte pour nous dans le suivi 
- on présente déjà les exercices en faisant référence aux fiches (=> exercices du chapitre vers fiche)
- si ils ont vraiment envie de résoudre des exercices correspondant à une fiche donnée, il suffit de parcourir le chapitre correspondant...

**Comment by npettiaux** [comment]
Malgré le fait que Catherine ne soit pas emballée, je crois que l'idée est bonne : permettre de faire une fiche en autonomie, avec des exercices graduellement plus difficile et par exemple séparé en 3 catégories (facile, normal, difficile), ce qui en passant défini «la norme» (= ce qui est attendu). Si les exercices sont présentés en faisant référence aux fiches, je ne comprends pas bien les réticences. Pourrais-tu m'expliquer de vive voix ? Merci

**Comment by npettiaux** [comment]
Je vais faire l'exercice de lier fiches et exercices en 3 catégories pour une fiche. Par laquelle me suggérez-vous de commencer ?

**Comment by mcodutti** [comment]
Je ne suis pas non plus convaincu.
Lors de toutes les évaluations, ils auront un énoncé et devront trouver quelle fiche pourrait les aider.
Il me parait dangereux qu'ils s’entraînent dans l'autre sens.
S'ils veulent travailler "en autonomie", ils peuvent prendre un chapitre et faire les exercices.
On essaie de les faire graduels et au début, la fiche dont on peut s'inspirer est explicitement donnée ou implicitement évidente; Puis, petit à petit, notamment dans tous les exercices récapitulatifs, ils doivent comprendre quelle fiche est la plus adaptée. Ca me parait suffisant?

**Comment by cuv** [comment]
Bon, je remarque que j'avais pas bien compris l'objectif des fiches. Je pensais que c'était un outil pour le travail en autonomie. Tu penses les donner lors des évaluations...
Peut être ajouter l'objectif et la méthode d'utilisation des fiches dans l'introduction de l'annexe A.
Mais ceci dépendra de la méthode pédagogique du prof... ?

**Comment by mcodutti** [comment]
En autonomie mais dans l'autre sens. Ils ont un exercice et se basent sur
une fiche qu'ils ont pendant l'apprentissage et plus pendant l'évaluation.
Dans les exercices finaux à eux de trouver la bonne fiche. Si on met
systématiquement les numéros d exercices dans les fiches, ils ne pourront
pas s'entraîner à trouver la bonne fiche.
Le 1 Jun. 2015 12:37, "cuv" <notifications@github.com> a écrit :

> Bon, je remarque que j'avais pas bien compris l'objectif des fiches. Je
> pensais que c'était un outil pour le travail en autonomie. Tu penses les
> donner lors des évaluations...
> Peut être ajouter l'objectif et la méthode d'utilisation des fiches dans
> l'introduction de l'annexe A.
> Mais ceci dépendra de la méthode pédagogique du prof... ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/issues/35#issuecomment-107392733>
> .
>

-- 
Haute École de Bruxelles
