### ISSUE TITLE
§7.5 - découpe - résumons

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV1-ALG-Syllabus-Algo#59]
Refaire qqchose de plus clair.
Idée de cuv: "Pour le résumé, un exemple ( division(a, b, reste)->resultat par ex.) et son tracé me semble bien."

**Comment by cathleruste** [comment]
division(a, b, reste)->resultat : rien n'est en entrée-sortie

**Comment by cathleruste** [comment]
Je peux rajouter un compteur d'appels (mais c'est bateau)

**Comment by cathleruste** [comment]
À relire

**Comment by cuv** [comment]
division(a, b IN: entier, reste OUT: entier)->entier algo qui retourne le résultat d'une division entière de a par b et qui donne en paramètre de sortie le reste de la division entière.

**Comment by cathleruste** [comment]
Mais alors, rien n'est en IN/OUT, c'est pour ça que j'ai rajouté un compteur bateau ^^ je trouve ça moche... mais je n'ai pas d'idée plus pertinente pour l'instant.
