### ISSUE TITLE
Lien avec labo Java

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV1-ALG-Syllabus-Algo#61]
Il faudra, en concertation avec DEV1-JAVL, choisir les exercices qui seront implémentés en Java et leur apposer le logo.

**Comment by npettiaux** [comment]
Et voir comment assurer une écriture coordonnée facile pour que les références croisées aient du sens et que la numérotation soit bonne (ex qhe dans le syllabus de java, on fasse référence au bon numéro dans le syllabus de ALG). Et aussi que la chronologie des matières dans les 2 activités d'apprentissage soient coordonnées.

**Comment by mcodutti** [comment]
Duplicate de #82
