### ISSUE TITLE
8.3.1 Ajouter une instruction après la boucle

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#66]
Montrer l'état des variables après la boucle par par exemple afficher "nous avons compté jusqu'à ", nb

**Comment by cuv** [comment]
idem pour les deux autres boucles ;)

**Comment by cathleruste** [comment]
Pas possible pour la boucle pour puisque la variable meurt à la fin.

**Comment by cuv** [comment]
Mais on peut mettre une instruction après la boucle pour et montrer dans le tableau de traçage que la variable de boucle est indéterminée ;)
