### ISSUE TITLE
Fiche 3 et 4 : pls retourner ? 

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#68]
Quand je lis ces deux fiches je ne sais pas si je peux ou non écrire plusieurs retourner. La première alternative des deux fiches sont-elles acceptées ou non? Et dans la fiche 3 il n'y a pas de solution avec un et un seul retourner... 

Bref les alternatives donneront-elles le max de point à l'évaluation par tous les profs?

**Comment by mcodutti** [comment]
Je relis ces fiches et je suis un peu embêté.
J'ai commencé à discuter des plusieurs "retourner" dans une fiche mais je vois que je les ai mis dans plusieurs fiches.
Je n'ai pas envie de re-commenter à chaque fois mais, d'un autre coté, les fiches ne sont pas lues séquentiellement.
Je me demande si ce ne serai pas mieux de : 
- Dans les fiches, ne garder que les alternatives qui ont un vrai sens pour l'exemple.
- Ajouter une annexe "Bonnes et mauvaises pratiques" avec tous ces bouts de code plus ou moins foireux qu'on pourrait discuter à l'aise.
- Dans les fiches, on pourrait faire des renvois vers cette nouvelle annexe.
Qu'en pensez-vous ?

**Comment by cathleruste** [comment]
Ça ne me parait pas évident à agencer mais puisque ça a l'air clair dans ta tête, ça me convient.

**Comment by mcodutti** [comment]
Justement, ca n'est pas clair dans la tête. Je vais faire un essai.
Le 3 Jul. 2015 13:33, "cathleruste" <notifications@github.com> a écrit :

> Ça ne me parait pas évident à agencer mais puisque ça a l'air clair dans
> ta tête, ça me convient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/issues/68#issuecomment-118322822>
> .
>

-- 
Haute École de Bruxelles

**Comment by cathleruste** [comment]
Dis-moi si/comment je peux aider.

**Comment by mcodutti** [comment]
En me relisant ;)
Je viens d'ajouter une annexe B avec des bonnes (et mauvaises) pratiques.
Est-ce que tu penses que ça peut être utile aux étudiants ?
Si c'est le cas, je modifierai les fiches pour faire des références à l'annexe B plutôt que me répéter.

**Comment by cuv** [comment]
Je les trouve bien ces bonnes/mauvaises pratiques...

**Comment by cathleruste** [comment]
J'aime bien le côté structuré et visuel de ces pratiques. C'est vraiment sympa !
Merci.

**Comment by ahallal** [comment]
Oui C’est bien d’avoir fait ainsi c’est plus clair.
Le 3 juil. 2015 22:25, "cathleruste" <notifications@github.com> a écrit :

> J'aime bien le côté structuré et visuel de ces pratiques. C'est vraiment
> sympa !
> Merci.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEB-ESI/DEV1-ALG-Syllabus-Algo/issues/68#issuecomment-118420965>
> .
>

-- 
Haute École de Bruxelles
