### ISSUE TITLE
Vocabulaire lié aux expressions

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV1-ALG-Syllabus-Algo#75]
Dans le syllabus et dans leur formation en général, on utilise quelques termes qui ne sont jamais explicitement définis : opérateur, opérande, expression, unaire, binaire, ternaire...
J'aimerais ajouter une sous-section au 5.3 ("Difficultés liées au calcul") qui s'appellerait : "Un peu de vocabulaire" et qui contiendrait : définition, exemples, exercices.
OK pour vous ?

**Comment by cuv** [comment]
très bonne idée [?]

**Comment by mcodutti** [comment]
J'ai écrit qqchose; j'en suis pas encore tout-à-fait content.
À relire.

**Comment by cuv** [comment]
à corriger : C'est pourquoi l'expression \Verb_a + b * c_  est équivalent à \Verb_(a + b) * c_ et pas à \Verb_a + (b * c)_.
