### ISSUE TITLE
Exo pas repris de l'année dernière

### ISSUE THREAD

**Issue by cathleruste** [HEB-ESI/DEV1-ALG-Syllabus-Algo#78]
Pour info, les exercices de 2014 pas repris dans le syllabus 2015.
Dans le syllabus 2014 : 
qui pourraient être dans le chap. 6 actuel :
- chap. 3 Q.7 : eq du 2e degré
- chap. 3 Q.8 : une petite minute
- chap. 3 Q.14 : quel jour serons-nous ?
- chap. 3 Q.15 : un peu de trigono ?
qui pourraient être dans le chap. 7 actuel :
- chap. 4 Q.4 : swap
qui pourraient être dans le chap. 8 actuel :
- chap. 6 Q.4 : max de nb
- chap. 6 Q.6 : placement d'un capital
- chap. 6 Q.8 : génération de suites
- chap. 6 Q.11 : binaire-décimal
- chap. 6 Q.12 : décimal-binaire
- chap. 6 Q.13 : pgcd
- chap. 6 Q.14 : ppcm
- chap. 6 Q.21 : imc
qui pourraient être dans le chap. 9.7.1 actuel :
- chap. 8 Q.2 : max/min
- chap. 8 Q.3 : indice max/min
qui pourraient être dans le chap. 12 actuel :
- chap. 8 Q.6 : plus grand écart absolu
- chap. 8 Q.7 : remplacement des valeurs
- chap. 8 Q.12 : cumul des ventes
- chap. 8 Q.15 : moyenne d'éléments
qui pourraient être dans le chap. des chaines actuel :
- chap. 8 Q.14 : palindromes
- chap. 8 Q.16 : OXO
- chap. 8 Q.19 : chiffre de César
- chap. 8 Q.20 : le caractère le plus présent

**Comment by mcodutti** [comment]
Je n'ai volontairement pas repris certains qui me plaisaient moins et gardé d'autres pour le chapitre sur les chaines (palindrome, César...).
Il faudrait faire le planning des séances et voir s'il manque des exercices pour certains chapitres/concepts.
Au fait, qui se charge de ce planning détaillé ?

**Comment by cathleruste** [comment]
J'ai commencé en juin, et là, il faut que je m'y remette... ^^
