### ISSUE TITLE
Chapitre sur les chaines

### ISSUE THREAD

**Issue by mcodutti** [HEB-ESI/DEV1-ALG-Syllabus-Algo#79]
Je viens d'ajouter un chapitre sur les chaines.
À relire...

**Comment by cathleruste** [comment]
13.6 : on parle encore du type caractère (cfr. *estLettre(car : caractère)* par exemple et *'a'* entre simples quotes) ... il n'existe pas mais c'est pourtant bien de pouvoir faire la distinction :s

**Comment by cathleruste** [comment]
idem 13.7

**Comment by cathleruste** [comment]
nombre(ch : chaine) → réel : ne peut-elle pas lancer une erreur si ch ne peut être converti ?

**Comment by cathleruste** [comment]
Merci pour le boulot !

**Comment by mcodutti** [comment]
Corrigé pour nombre(chaine) et les ' qui deviennent des ".
Pour caractère, on peut le présenter comme un type à part entière (avec conversion automatique de et vers chaine) ou comme un raccourci pour dire "chaine de 1 caractère", c'est kif-kif. Je ne pense pas qu'il faille aller plus loin en algo.
Merci pour la relecture.

**Comment by cuv** [comment]
pourquoi ne pas faire commencer l'indice à 0 (comme pour les tableaux et en python)? Cela uniformise notre logique de notation et enlève un sujet de problème pour les étudiants.

**Comment by cuv** [comment]
13.7 : s/estMajuscule(car : caractère) → booléen... minuscule./estMajuscule(car : caractère) → booléen... majuscule

**Comment by mcodutti** [comment]
Pour 0 ou 1, j'ai hésité. Je me suis dit que : 

1) c'est plus naturel d'écrire "pour i de 1 à long(s)" que "pour i de 0 à long(s)-1"
2) il y a peu d'exercices sur les chaines en Java
3) comme on commence à 0  avec les tableaux, ils s'essayent à autre chose; je ne voudrais pas qu'ils ne soient plus capables d'écrire un algo si ça commence à 0.

Mais je n'en fais pas une fixette; on peut changer si la majorité le préfère.

**Comment by cathleruste** [comment]
Je trouve aussi que c'est plus naturel de dire que le premier élément d'une chaine est le numéro 1.
Je n'ai pas changé.
