### ISSUE TITLE
Passage de paramètres

### ISSUE THREAD

**Issue by eythanlevy** [HEB-ESI/DEV1-ALG-Syllabus-Algo#92]
J'ai rajouté une nouvelle figure tout à la fin du chapitre 7. Qu'en pensez-vous?

**Comment by cathleruste** [comment]
Merci pour le boulot Eythan.

- Je ne sais pas si c'est faisable mais je préfèrerais que les flèches du code appelé se trouvent en tout début (juste après "algorithme") en cas de paramètre en entrée et en toute fin (juste avant "fin algorithme") en cas de paramètre en sortie
- dans le cas b. 
-- a vaut 3.14 mais est déclaré entier
-- x ne doit pas prendre de valeur dans le code appelant
- dans le cas c. 
-- a est noté en sortie uniquement au lieu d'entrée-sortie

Ce n'est pas facile de gérer la position de l'image sous LaTeX, je ne sais pas si c'est faisable de le mettre avant le 7.6

Merci

**Comment by eythanlevy** [comment]
Merci Catherine. J'ai pushé une nouvelle version incluant toutes tes remarques. Qu'en penses-tu?

**Comment by mcodutti** [comment]
Merci.
