### ISSUE TITLE
complexité: exercices

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#96]
p105 la question 8 demande la connaissance d'algo non vu

**Comment by cathleruste** [comment]
Je n'ai pas de question 8 à la page 105. Peux-tu préciser la numérotation du chapitre-paragraphe stp ?

**Comment by cuv** [comment]
L'exercice "calcul de complexités"

**Comment by mcodutti** [comment]
Je supprime juste celui sur le tri. Il me semble qu'ils peuvent comprendre les autres et imaginer la solution et en déduire la complexité même s'ils ne peuvent pas l'écrire dans le détail. On verra à l'usage.
