### ISSUE TITLE
tableaux exercices

### ISSUE THREAD

**Issue by cuv** [HEB-ESI/DEV1-ALG-Syllabus-Algo#97]
p116 ex7 ressemble beaucoup à l'ex 12 p 94 (ch9)

**Comment by cathleruste** [comment]
idem pour la numérotation des pages

**Comment by cuv** [comment]
l'exercice "lancer de deux dés" ch12 et l'exercice "lancers de dé" du chapitre 9

**Comment by mcodutti** [comment]
En effet, je vais les laisser quand même. On verra à l'usage.
